import "./globals.css";

import localFont from "next/font/local";

const MonaSans = localFont({
  src: "../fonts/Mona-Sans.woff2",
  display: "swap",
  variable: "--font-mona-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html className={`${MonaSans.variable}`} lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">{children}</main>
      </body>
    </html>
  );
}
